
# This file is the configuration file for your dbt project. It contains metadata about your project, such as its name and version, as well as configurations for how dbt should behave when running models, tests, and other operations.
name: 'olist_ecommerce_supplychain'
version: '1.0.0'

# This setting specifies the profile that dbt should use when connecting to your data warehouse. The profile contains the connection details (like host, user, password, etc.) for your database. Make sure that the profile name matches one of the profiles defined in your `profiles.yml` file.
profile: 'olist_ecommerce_supplychain'

# This section defines the paths where dbt will look for different types of files in your project. You can customize these paths if you have a different directory structure.
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:         # This section specifies the directories that dbt should clean up when you run the `dbt clean` command. Cleaning these directories removes any compiled artifacts, temporary files, or other outputs generated by dbt during its operations. This is useful for maintaining a clean working environment and ensuring that old or unnecessary files do not interfere with your current work.
  - "target"
  - "dbt_packages"


# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models
models:
  olist_ecommerce_supplychain:
    staging:
      +materialized: view
    marts:
      +materialized: table
